[package]
name = "rust-structure"
version = "0.1.0"
authors = ["numbp"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rust-structure"
path = "main.rs"
